Fix ANO linking warning
nvidia-holoscan/holohub pull request #463
Opened 2024-08-08 20:36 UTC by JohnMoon-VTS

Currently, when building an app that uses the Advanced Network Operator (ANO), CMake throws some warnings:

```
CMake Warning at operators/advanced_network/CMakeLists.txt:87 (target_link_libraries):
  Target "<target>" requests linking to directory
  "/usr/lib/x86_64-linux-gnu".  Targets may link only to libraries.  CMake is
  dropping the item.
```

Like it says, there are directories being passed into target_link_libraries with -L which is not supported.

Instead, let's use target_link_directories which is already being used in the ANO CMakeLists.txt file to pass those DPDK and DOCA directories.

2024-08-12 20:48 UTC, jjomier commented
@cliffburdick can you review?

2024-08-12 20:50 UTC, cliffburdick commented on operators/advanced_network/CMakeLists.txt
> +target_link_directories(advanced_network_common PUBLIC ${DPDK_LIBRARY_DIRS})
Can you just combine the DOCA and DPDK libs into a single line?

2024-08-12 20:51 UTC, cliffburdick commented on operators/advanced_network/CMakeLists.txt
> +target_link_libraries(advanced_network_common PUBLIC -ldoca_gpunetio libdoca_gpunetio_device.a -ldoca_common -ldoca_argp -ldoca_eth -ldoca_flow)
Same thing --combine into one line?

2024-08-12 20:51 UTC, cliffburdick requested changes
Consolidating a couple lines

2024-08-15 21:22 UTC, jjomier commented
@cliffburdick are we good to merge?

2024-08-15 21:42 UTC, cliffburdick commented
> @cliffburdick are we good to merge?

I left a comment above that I don't think has addressed yet

2024-08-15 21:43 UTC, cliffburdick commented
> @cliffburdick are we good to merge?

Yes, sorry, just saw it was addressed.

2024-08-15 21:44 UTC, jjomier commented
> > @cliffburdick are we good to merge?
> 
> Yes, sorry, just saw it was addressed.

Can you approve the review?

2024-08-20 15:30 UTC, JohnMoon-VTS commented
@cliffburdick, I went ahead and rebased - this should be ready for review. Thanks!

2024-08-20 15:31 UTC, cliffburdick approved these changes

2024-08-26 15:26 UTC, JohnMoon-VTS commented
@jjomier, I just rebased again. Anything else blocking merge?

2024-08-26 17:17 UTC, cliffburdick approved these changes

2024-08-26 17:30 UTC, merged