Add psd_pipeline application
nvidia-holoscan/holohub pull request #632
Opened 2024-12-11 17:34 UTC by JohnMoon-VTS

Add a new ANO-driven signal processing pipeline that ingests high-rate VITA 49 IQ data and computes/packetizes averaged, lower-rate, VITA 49.2 spectral PSDs. A few operators that may be reused are added under the common "operators" directory as well.

Note: build will require #627 to merge.

2025-01-17 16:41 UTC, dylan-eustice commented
So this has implementations of both sending and receiving VITA 49 flows with the ANO? Very cool.

2025-01-17 16:51 UTC, JohnMoon-VTS commented
The VITA 49 RX is done with ANO, yes. But the VITA 49 PSDs being sent out the other side of the pipeline are being packetized and sent by the [`vita49_psd_packetizer` operator](https://github.com/JohnMoon-VTS/holohub/tree/ano-psd-pipeline/operators/vita49_psd_packetizer) (in the CPU). These PSD packets are low rate and we're using a third-party library for the packetization that didn't play nice with `nvcc`, so this seemed like the path of least resistance.

If you think it'd make more sense to send them out via ANO as well, we're happy to consider it!

2025-01-21 16:08 UTC, tbirdso requested changes
Thanks @JohnMoon-VTS for your project submission! I've added a few high level comments, with one potential blocker regarding licensing.

@dylan-eustice would you mind taking a review pass as you're more familiar with the domain?

2025-01-21 16:08 UTC, tbirdso commented on operators/vita49_psd_packetizer/context.cpp
> + */
I'm concerned about providing and compiling LGPL source code as part of this project. LGPL is typically not compatible with the default Apache license used in HoloHub projects unless dynamically linked. In this case `context.cpp` is directly compiled as part of the PSD application, meaning any derived PSD application components likely would need to be LGPL licensed as well.

Some possible options:
- Does `vrtgen` maintain a package that could be dynamically linked?
- Could `vrtgen` generate files under a permissive license? You might reach out to the `vrtgen` maintainers to understand options here.
- We might accept a HoloHub contribution if all components are properly licensed for compatibility with LGPL components, but will require further discussion. cc @jjomier for a second opinion.

2025-01-21 16:08 UTC, tbirdso commented on operators/vita49_psd_packetizer/CMakeLists.txt
> +)
Note that the LGPL `context.cpp` component is typically incompatible with other Apache-2.0 sources.

2025-01-21 17:13 UTC, tbirdso commented on operators/vita49_psd_packetizer/context.cpp
> + */
After offline discussion with @jjomier we'd like to avoid committing LGPL code to HoloHub to minimize risk of exposure to other projects.

_If it is not possible to use permissive licensing by updating `vrtgen` or using a different library_, then we'll request the following app changes:
- Instead of committing LGPL code, fetch `vrtgen` dynamically and generate context sources at config/build time. This might be accomplished with CMake's `FetchContent`.
- Instead of compiling LGPL code with Apache-2.0 code, isolate `vrtgen` generated code in a dedicated CMake shared library target ([doc](https://cmake.org/cmake/help/latest/command/add_library.html#id2)). Then, have other app components dynamically link against that target.
- Explicitly document in the operator and app READMEs that LGPL code is included via `vrtgen`.
- Sign-off on the commit (`git commit -s`) to attest that licenses are properly respected. (We always require this for HoloHub contributions)

2025-01-21 17:26 UTC, JohnMoon-VTS commented on operators/data_writer/data_writer.cu
> +    // io::write_csv(psd_host, "psdOut.csv", ",");
I don't believe so - we've talked with @cliffburdick offline about this and he was able to reproduce, but I don't see a GitHub issue for it.

2025-01-21 17:26 UTC, JohnMoon-VTS commented on operators/data_writer/README.md
> +copies the data to a host tensor, then writes the data out to a binary file.
Okay, will do.

2025-01-21 17:27 UTC, JohnMoon-VTS commented on applications/psd_pipeline/advanced_network_connectors/vita49_rx.cu
> +      // TODO: when context changes, we should flush data
Yes, we intentionally left that as a TODO for now. There's some non-trivial logic that needs to be added to handle this case and it's fairly minor for us at this stage.

2025-01-21 17:27 UTC, JohnMoon-VTS commented on applications/psd_pipeline/README.md
> +## Overview
Yes, will do!

2025-01-21 17:29 UTC, JohnMoon-VTS commented on applications/psd_pipeline/CMakeLists.txt
> +set(CMAKE_CUDA_ARCHITECTURES "70;80;90")
We do require portability for this application. We're moving the built container to an embedded system.

2025-01-21 17:34 UTC, JohnMoon-VTS commented on operators/vita49_psd_packetizer/context.cpp
> + */
I understand why you're hesitant to let LGPL code into HoloHub. We'll work a solution on our end (maybe just doing what you suggest above).

2025-01-21 18:37 UTC, cliffburdick commented on operators/data_writer/data_writer.cu
> +    // io::write_csv(psd_host, "psdOut.csv", ",");
It's something about mixing the python version that's used in matx and holohub. I didn't have time to debug more, but this function works fine in a standalone environment. When it's in holohub there seems to be some paths and symbols that are mixed up.

2025-01-21 22:03 UTC, JohnMoon-VTS commented
@tbirdso, I think this is ready for re-review. We moved out the LGPL code to a repo on our end that gets pulled in at build-time.

2025-01-23 03:00 UTC, tbirdso approved these changes
Thanks @JohnMoon-VTS for the updates and for moving the LGPL sources to a dedicated repo. You may want to consider making the `vita49_psd` [external target](https://github.com/vts-i/vita49-psd/blob/main/CMakeLists.txt#L15) a shared rather than static library if you are distributing binaries at any time in reflection of LGPL compliance. (_not legal advice_)

Updates look good to me, PR needs approval from an ANO stakeholder. Let me follow up.

2025-01-24 21:31 UTC, cliffburdick reviewed
This looks great! I think it showcases many different tools together very well. How easy is it for a user other than you to run?

2025-01-24 21:31 UTC, cliffburdick commented on applications/psd_pipeline/advanced_network_connectors/vita49_rx.h
> +inline uint64_t bswap_64_h(uint64_t val) {
For future reference, this should be used on the device: https://docs.nvidia.com/cuda/cuda-math-api/cuda_math_api/group__CUDA__MATH__INTRINSIC__INT.html?highlight=__byte_perm#_CPPv411__byte_permjjj

It's likely not faster for the 16-bit endian swap, but it will be for 32/64.

2025-01-24 21:31 UTC, cliffburdick commented on operators/fft/fft.cu
> +    auto out = outputs.Slice<2>({static_cast<index_t>(channel_num), 0, 0},
same comment on using `slice()` instead of the member function

2025-01-24 21:31 UTC, cliffburdick commented on operators/high_rate_psd/high_rate_psd.cu
> +    auto out = outputs.Slice<2>({static_cast<index_t>(channel_num), 0, 0},
`slice()`

2025-01-24 21:31 UTC, cliffburdick commented on operators/low_rate_psd/low_rate_psd.cu
> +    (maxima = ones() * 127.0).run();
Isn't this the same as `(maximum = 127.0).run();`?

2025-01-24 21:31 UTC, cliffburdick commented on operators/low_rate_psd/low_rate_psd.cu
> +    auto out = outputs.Slice<1>({static_cast<index_t>(channel_num), 0},
`slice()`

2025-01-24 21:42 UTC, JohnMoon-VTS commented on applications/psd_pipeline/advanced_network_connectors/vita49_rx.cu
> +  auto meta = metadata();
Yeah, that was us. By this stage, it appears to be low enough overhead that it's not causing an issue for us. But yeah, in the future, any more perf we could get out of the metadata passing would be welcome!

2025-01-24 21:42 UTC, JohnMoon-VTS commented on applications/psd_pipeline/advanced_network_connectors/vita49_rx.cu
> +  auto data = channel->rf_data.Slice<2>({static_cast<index_t>(channel->cur_idx), 0, 0},
Understood - will update!

2025-01-24 21:43 UTC, JohnMoon-VTS commented on applications/psd_pipeline/advanced_network_connectors/vita49_rx.h
> +inline uint64_t bswap_64_h(uint64_t val) {
Okay, I'll try out using the native CUDA functions for the swap. We ended up just using these since we knew the logic worked correctly from REDHAWK experience.

2025-01-24 21:44 UTC, JohnMoon-VTS commented on operators/low_rate_psd/low_rate_psd.cu
> +    (maxima = ones() * 127.0).run();
Probably, yeah! We knew this initialization looked silly, but I couldn't find anything in the MatX docs for initializing a tensor to all one value like this. Will update.

2025-01-24 21:47 UTC, JohnMoon-VTS commented
Thanks for the detailed review, @cliffburdick! I'll incorporate your feedback as soon as I can.

> How easy is it for a user other than you to run?

It should be pretty easy for anyone who has a VITA 49 data source of some kind. Some parameters would need to be tweaked for the particular format (e.g. how many samples come in a packet) and particular hardware (e.g. memory sizes and PCIe addresses), but those should be called out in the README.

2025-01-29 17:47 UTC, JohnMoon-VTS commented
@cliffburdick, I've made the changes you've requested and rebased on top of 2.9.0. I think this is ready for re-review. Thanks!

2025-02-03 18:37 UTC, tbirdso commented
Approved for merge in offline discussion with @cliffburdick . Thank you @JohnMoon-VTS for making the requested changes.

2025-02-03 18:37 UTC, merged